import './style.css'
import App from './App.svelte'

const app = new App({
  target: document.getElementById('app')
})

// Global right-click handler — captures before Wails can intercept.
// Uses 'pointerdown' which fires at the earliest possible point.
document.addEventListener('pointerdown', (e) => {
  if (e.button === 2) {
    e.preventDefault()
    e.stopImmediatePropagation()
    // @ts-ignore — generated by Wails at build time
    window.go?.main?.App?.ShowContextMenu?.()
  }
}, true) // 'true' = capture phase, fires before bubble

// Also suppress the default context menu entirely
document.addEventListener('contextmenu', (e) => {
  e.preventDefault()
  e.stopImmediatePropagation()
}, true)

export default app
